# Generated by Django 5.1.3 on 2025-02-24 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата та час')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
            ],
            options={
                'verbose_name': 'Messages from the contact form',
                'verbose_name_plural': 'Messages from the contact form',
                'ordering': ['-created_at'],
            },
        ),
    ]
