# Generated by Django 5.1.3 on 2025-03-13 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of sending'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
