# Generated by Django 5.1.3 on 2026-03-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("AwaitingPayment", "Awaiting Payment"),
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Refunded", "Refunded"),
                ],
                default="AwaitingPayment",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("stripe", "Stripe")], default="stripe", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("provider_checkout_session_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("provider_payment_intent_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("checkout_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("raw_last_event", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="payments", to="orders.order"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=20)),
                ("provider_event_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=255)),
                ("payload_hash", models.CharField(max_length=64)),
                ("raw_payload", models.TextField(blank=True)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="orderpayment",
            constraint=models.UniqueConstraint(
                fields=("order", "provider", "attempt_number"),
                name="uniq_order_provider_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_event_id"),
                name="uniq_provider_event_id",
            ),
        ),
    ]
