name: Deploy Artist Portfolio App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t pro100grammer/artist_backend:latest ./artist_portfolio
          docker build -t pro100grammer/artist_frontend:latest ./frontend/3d-gallery
          docker push pro100grammer/artist_backend:latest
          docker push pro100grammer/artist_frontend:latest

      - name: Deploy Backend to Render
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_BACKEND_ID }}" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d ''

      - name: Deploy Frontend to Render
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_FRONTEND_ID }}" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d ''